### ISSUE TITLE
Compile error when using the repo as reference

### ISSUE THREAD

**Issue by Swepilot** [vbalagovic/flutter_scalable_ocr#13]
When referencing this repo (or a fork of it) directly in pubspec.yaml I get a compilation error:

_Error (Xcode): ../../.pub-cache/git/flutter_scalable_ocr-7e74e46c3ecbacf791364f9be309e62a29c6b544/lib/flutter_scalable_ocr.dart:51:24: Error: Can't declare a member that conflicts with an inherited one._

Using version 2.0.0 from pub.dev does not produce this error.

Issue seemes to be introduced with this commit: https://github.com/vbalagovic/flutter_scalable_ocr/blame/7e74e46c3ecbacf791364f9be309e62a29c6b544/lib/flutter_scalable_ocr.dart#L51

Chaning to `ScalableOCRState createState() => ScalableOCRState();` solves the issue

**Comment by vbalagovic** [comment]
[](url)
