### ISSUE TITLE
Require old version of google_mlkit

### ISSUE THREAD

**Issue by mrahmadt** [vbalagovic/flutter_scalable_ocr#19]
flutter_scalable_ocr require an old version of google_mlkit 

% flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name                   Current  Upgradable  Resolvable  Latest  

direct dependencies:          
google_mlkit_commons           *0.3.0   *0.3.0      *0.3.0      0.6.1   
google_mlkit_text_recognition  *0.6.0   *0.6.0      *0.6.0      0.11.0  

Why dependency upgrade is required? seems the old version is not working any more. It's not able to reorganize any text

**Comment by vbalagovic** [comment]
Updated to newer dependencies, in few days I'll update to the latest as separate version (requires high version of iOS)
