### ISSUE TITLE
recognize text in Japanese

### ISSUE THREAD

**Issue by higthu** [vbalagovic/flutter_scalable_ocr#3]
thank you for your sharing, it helps me a lot. However I have some Japanese words I need to detect and recognize. But it does not work.

**Comment by vbalagovic** [comment]
Hi, thanks. Japanese was not in a supported language in ML kit text recognition v1 
https://developers.google.com/ml-kit/vision/text-recognition/languages

But I can see now that v2 is in beta and they added Japanese. I'll check the possible update when I get some time but you can use this source code and combine it with a newer version of the ML kit for the test.
