### ISSUE TITLE
can we turn on flash / torch camera ?

### ISSUE THREAD

**Issue by yogithesymbian** [vbalagovic/flutter_scalable_ocr#5]
i only read **readme.md** and not install yet.
but i looking for first information, want to know..., this package support for torch / flash ? and how about other device ( ios ) also can be working ?
thankyou ...

**Comment by vbalagovic** [comment]
Hi, it works on iOS and Android, the torch is not implemented through this package, but you can add torch on/off on the screen where you're using this package. But good idea, I will implement it when I upgrade everything to 3.10 :)

**Comment by yogithesymbian** [comment]
Thanks for your feedback! I'm glad to hear that the package works on both iOS and Android. Adding the torch on/off functionality sounds like a great idea, especially for enhancing user experience. Looking forward to the upgrade to version 3.10 and seeing the new features. Keep up the good work!

**Comment by yogithesymbian** [comment]
which package ? 
```
torch [EnableTorchExistentUserException: There is an existent camera user, cannot enable torch: android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): setTorchMode:2065: Torch for camera "0" is not available due to an existing camera user]
```
i use `torch_light: ^1.0.0` still looking for toggleFlash like on qr_scanner ,,,

**Comment by vbalagovic** [comment]
torch support added
